name: Tests

on:
  push:
    branches:
      - 'master'
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.0]
        laravel: ['8.*']
        exclude:
          - php: 7.3
            laravel: 9.*
          - php: 7.4
            laravel: 9.*

    name: 'PHP ${{ matrix.php }} / Laravel ${{ matrix.laravel }}'

    steps:

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          collation server: 'utf8_general_ci'
          mysql version: '8.0'
          mysql database: 'laravel'
          mysql root password: 'root'

      - uses: actions/checkout@master

      # Configure PHP
      - name: Select PHP version
        uses: shivammathur/setup-php@master
        with:
          php-version: '${{ matrix.php }}'
          extensions: mbstring, pdo_sqlite, fileinfo, gd
          coverage: none

      # Configure NPM
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      # Install PHP dependencies
      - name: Install Composer dependencies
        run: composer require "illuminate/support:${{ matrix.laravel }}"

      # Install legacy factories for Laravel 8/9
      - name: Install legacy factories for Laravel
        if: ${{ matrix.laravel == '8.*' || matrix.laravel == '9.*' }}
        run: composer create-project laravel/laravel:^${{matrix.laravel}} laravel && cd laravel

      # Display installed laravel version
      - name: Show laravel version
        run: composer show laravel/framework

      # Install NPM dependencies
      - name: Install Dependencies
        run: npm install

      # Build static assets
      - name: Compile Assets
        run: npm run prod

      # Run phpunit tests
      - name: Run tests
        run: ./vendor/bin/phpunit
